<?xml version="1.0" encoding="UTF-8"?>
<project name="IbnuCashierTubes" default="default" basedir="." xmlns:sonar="antlib:org.sonar.ant">
    <description>Builds, tests, and runs the project IbnuCashierTubes.</description>
    
    <import file="nbproject/build-impl.xml"/>


    <path id="sonar.classpath">
        <fileset dir="lib">
            <include name="*.jar"/>
        </fileset>
    </path>

    <taskdef uri="antlib:org.sonar.ant" resource="org/sonar/ant/antlib.xml" classpathref="sonar.classpath"/>

    <target name="sonar" depends="compile">
         <property name="sonar.host.url" value="http://localhost:9000" />
         <property name="sonar.projectKey" value="ibnuCashier-tubes-pbo" />
         <property name="sonar.projectName" value="Ibnu Cashier PBO" />
         <property name="sonar.projectVersion" value="1.0" />
         <property name="sonar.sources" value="src" />
         
         <property name="sonar.java.binaries" value="build/web/WEB-INF/classes" />
         
         <property name="sonar.java.libraries" value="lib/*.jar" />
         
         <property name="sonar.login" value="sqp_98137c651007ecc94bb0a41f86241f41d2c4c2c3" />
         
         <sonar:sonar />
    </target>

</project>